module.exports = [
	'senior backend',
	'senior back-end',
	'senior back end',
	'senior backend engineer',
	'senior software developer - backend',
	'software developer backend',
	'software developer back-end',
	'software engineer backend',
	'software engineer back end',
	'software engineer - back end',
	'software developer - backend',
	'software developer - back end',
	'software development engineer - backend',
	'backend software developer',
	'back end software developer',
	'backend engineer',
	'backend developer',
	'back-end developer',
	'back end developer',
	'back end engineer',
	'backend developer',
	'backend engineer',
	'backend',
	'back end',
	'back-end',
	'nodejs developer',
	'nodejs',
	'ruby on rails developer',
	'ruby on rails',
	'django developer',
	'django',
	'full stack'
]
