module.exports = [
	'senior graphic designer',
	'senior product designer',
	'senior ux designer',
	'senior ui designer',
	'senior ux/ui',
	'senior ux / ui',
	'design lead',
	'senior experience designer',
	'senior interaction designer',
	'senior mobile designer',
	'senior mobile ui designer',
	'senior mobile ux',
	'graphic designer',
	'product designer',
	'ux designer',
	'ui designer',
	'ux/ui',
	'ux / ui',
	'design lead',
	'experience designer',
	'interaction designer',
	'mobile designer',
	'mobile ui designer',
	'mobile ux'
]
