module.exports = [
	'senior frontend',
	'senior front-end',
	'senior front end',
	'senior frontend engineer',
	'senior software developer - frontend',
	'software developer frontend',
	'software developer front-end',
	'software engineer frontend',
	'software engineer front end',
	'software engineer - front end',
	'software developer - frontend',
	'software developer - front end',
	'software development engineer - frontend',
	'frontend software developer',
	'front end software developer',
	'frontend engineer',
	'frontend developer',
	'front-end developer',
	'front end developer',
	'front end engineer',
	'frontend developer',
	'frontend engineer',
	'ui engineer',
	'ui developer',
	'frontend ui engineer',
	'frontend ui developer',
	'front end ui developer',
	'javascript engineer',
	'javascript developer',
	'frontend',
	'front end',
	'front-end',
	'js engineer',
	'angular.js developer',
	'angularjs developer',
	'angular js developer',
	'react.js developer',
	'reactjs',
	'react js',
	'jquery developer',
	'jquery engineer',
	'full stack'
]
