module.exports = {
	'senior android' : 'Senior Android Developer',
	'senior android engineer' : 'Senior Android Developer' ,
	'senior software developer - android' : 'Senior Android Developer',
	'software developer android' : 'Software Developer - Android',
	'software engineer android' : 'Software Engineer - Android',
	'software engineer - android' : 'Software Engineer Android',
	'software developer - android' : 'Software Developer - Android',
	'software development engineer - android' : 'Software Development Engineer - Android',
	'mobile software developer' : 'Mobile Developer',
	'android engineer' : 'Android Engineer',
	'android developer': 'Android Developer',
	'mobile engineer' : 'Mobile Engineer',
	'mobile developer' : 'Mobile Developer',
	'android app developer' : 'Android App Developer',
	'android app engineer' : 'Android App Engineer',
	'mobile app developer' : 'Mobile App Developer',

	'senior backend' : 'Senior Backend Engineer',
	'senior back-end' : 'Senior Backend Engineer',
	'senior back end' : 'Senior Backend Engineer',
	'senior backend engineer' : 'Senior Backend Engineer',
	'senior software developer - backend' : 'Senior Software Developer - Backend',
	'software developer backend' : 'Software Developer Backend',
	'software developer back-end' : 'Software Developer Backend',
	'software engineer backend' : 'Software Engineer Backend',
	'software engineer back end' : 'Software Engineer Backend',
	'software engineer - back end' : 'Software Engineer - Backend',
	'software developer - backend' : 'Software Developer - Backend',
	'software developer - back end' : 'Software Developer - Backend',
	'software development engineer - backend' : 'Software Development Engineer - Backend',
	'backend software developer' : 'Backend Software Developer',
	'back end software developer' : 'Backend Software Developer',
	'backend engineer' : 'Backend Engineer',
	'backend developer' : 'Backend Developer',
	'back-end developer' : 'Backend Developer',
	'back end developer' : 'Backend Developer',
	'back end engineer' : 'Backend Engineer',
	'backend developer' : 'Backend Developer',
	'backend engineer' : 'Backend Engineer',
	'backend' : 'Backend Developer',
	'back end' : 'Backend Developer',
	'back-end' : 'Backend Developer',
	'nodejs developer' : 'NodeJS Developer',
	'nodejs' : 'NodeJS Developer',
	'ruby on rails developer' : 'Ruby on Rails Developer',
	'ruby on rails' : 'Ruby on Rails Developer',
	'django developer' : 'Django Developer',
	'django' : 'Django Developer',

	'senior graphic designer' : 'Senior Graphic Designer',
	'senior product designer' : 'Senior Product Designer',
	'senior ux designer' : 'Senior UX Designer',
	'senior ui designer' : 'Senior UI Designer',
	'senior ux/ui' : 'Senior UI/UX Designer',
	'senior ux / ui' : 'Senior UI/UX Designer',
	'design lead' : 'Design Lead',
	'senior experience designer' : 'Senior Experience Designer',
	'senior interaction designer' : 'Senior Interaction Designer',
	'senior mobile designer' : 'Senior Mobile Designer',
	'senior mobile ui designer' : 'Senior Mobile UI Designer',
	'senior mobile ux' : 'Senior Mobile UX Designer',
	'graphic designer' : 'Graphic Designer',
	'product designer' : 'Product Designer',
	'ux designer' : 'UX Designer',
	'ui designer' : 'UI Designer',
	'ux/ui' : 'UX/UI Designer',
	'ux / ui' : 'UX/UI Designer',
	'design lead' : 'Design Lead',
	'experience designer' : 'Experience Designer',
	'interaction designer' : 'Interaction Designer',
	'mobile designer' : 'Mobile Designer',
	'mobile ui designer' : 'Mobile UI Designer',
	'mobile ux' : 'Mobile UX Designer',

	'devops' : 'DevOps Engineer',
	'dev ops' : ' DevOps Engineer',

	'senior frontend' : 'Senior Frontend Developer',
	'senior front-end' : 'Senior Frontend Developer',
	'senior front end' : 'Senior Frontend Developer',
	'senior frontend engineer' : 'Senior Frontend Engineer',
	'senior software developer - frontend' : 'Senior Software Developer - Frontend',
	'software developer frontend' : 'Senior Software Developer - Frontend',
	'software developer front-end' : 'Software Developer Frontend',
	'software engineer frontend' : 'Software Developer Frontend',
	'software engineer front end' : 'Software Engineer Frontend',
	'software engineer - front end' : 'Software Engineer -  Frontend',
	'software developer - frontend' : 'Software Developer - Frontend',
	'software developer - front end' : 'Software Developer - Frontend',
	'software development engineer - frontend' : 'Software Development Engineer - Frontend',
	'frontend software developer' : 'Frontend Software Developer',
	'front end software developer' : 'Frontend Software Developer',
	'frontend engineer' : 'Frontend Engineer',
	'frontend developer' : 'Frontend Developer',
	'front-end developer' : 'Frontend Developer',
	'front end developer' : 'Frontend Developer',
	'front end engineer' : 'Frontend Engineer',
	'frontend developer' : 'Frontend Developer',
	'frontend engineer' : 'Frontend Engineer',
	'ui engineer' : 'UI Engineer',
	'ui developer' : 'UI Developer',
	'frontend ui engineer' : 'Frontend UI Engineer',
	'frontend ui developer' : 'Frontend UI Developer',
	'front end ui developer' : 'Frontend UI Developer',
	'javascript engineer' : 'Javascript Engineer',
	'javascript developer' : 'Javascript Developer',
	'frontend' : 'Frontend Engineer',
	'front end' : 'Frontend Engineer',
	'front-end' : 'Frontend Engineer',
	'js engineer' : 'Javascript Engineer',
	'angular.js developer' : 'AngularJS Developer',
	'angularjs developer' : 'AngularJS Developer',
	'angular js developer' : 'AngularJS Developer',
	'react.js developer' : 'ReactJS Developer',
	'reactjs' : 'ReactJS Developer',
	'react js' : 'ReactJS Developer',
	'jquery developer' : 'JQuery Developer',
	'jquery engineer' : 'JQuery Engineer',
	'full stack' : 'Full Stack Engineer',

	'senior ios' : 'Senior iOS Developer',
	'senior ios engineer' : 'Senior iOS Engineer',
	'senior software developer - ios' : 'Senior Software Developer - iOS',
	'software developer ios' : 'Software Developer - iOS',
	'software engineer ios' : 'Software Engineer iOS',
	'software engineer - ios' : 'Software Engineer - iOS',
	'software developer - ios' : 'Software Developer - iOS',
	'software development engineer - ios' : 'Software Development Engineer - iOS',
	'mobile software developer' : 'Mobile Software Developer',
	'ios engineer' : 'iOS Engineer',
	'ios developer' : 'iOS Developer',
	'mobile engineer' : 'Mobile Engineer',
	'mobile developer' : 'Mobile Developer',
	'ios app developer' : 'iOS App Developer',
	'ios app engineer' : 'iOS App Engineer',
	'mobile app developer' : 'Mobile App Developer',

	'senior product manager' : 'Senior Product Manager',
	'product manager' : 'Product Manager',
	'product designer' : 'Product Designer',
	'senior product' : 'Senior Product Manager',
	'growth hacker' : 'Growth Hacker',
	'product growth' : 'Product Growth Manager',
	'growth manager' : 'Growth Manager',

	'software development engineer' : 'Software Development Engineer',
	'sde 1' : 'SDE 1',
	'sde 2' : 'SDE 2',
	'sde 3' : 'SDE 3',
	'sde i' : 'SDE 1',
	'sde ii' : 'SDE 2',
	'sde iii' : 'SDE 3',
	'sde' : 'Software Development Engineer',

	'sdet' : 'SDET',
	'software development engineer test' : 'SDET',
	'tester' : 'Tester',
	'app tester' : 'App Tester',
	'web tester' : 'Web Tester'

}
